---
# tasks file for git.role
- include_tasks: variables.yml

- include_tasks: setup-CentOS.yml
  when: ansible_distribution == 'CentOS'

- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: setup-Alpine.yml
  when: ansible_distribution == 'Alpine'

- include_tasks: install-git.yml

- import_tasks: remove-CentOS.yml
  when: ansible_distribution == 'CentOS'
- import_tasks: remove-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
- import_tasks: remove-Alpine.yml
  when: ansible_distribution == 'Alpine'
