---
- name: Remove package version of git (Centos)
  yum:
    name: git
    state: absent
- name: add path in (Centos)
  blockinfile:
    path: /home/{{ ansible_ssh_user }}/.bash_profile
    block: |
      export PATH=$PATH:/usr/local/bin