---
- name: Remove package version of git  (alpine
  apk:
    name: git
    state: absent
- name: add path on (alpine)
  blockinfile:
    path: /home/{{ ansible_ssh_user }}/.profile
    block: |
      export PATH=$PATH:/usr/local/bin